version: '3'

services:
  portainer:
    image: docker.javamall.com.cn:5001/javashop-infrastructure/portainer:latest 
    ports:
        - 9000:9000
    networks:
      - javashop_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  consul:
    image: docker.javamall.com.cn:5001/javashop-infrastructure/consul:latest
    ports:
        - 8500:8500
    networks:
        - javashop_network
    deploy:
      replicas: 1
networks:
  javashop_network:
    external: true
